/**
 * Tests for delegation ID generation and validation.
 */

import { describe, it, expect } from 'vitest';
import { generateId, generateUniqueId, isValidId } from '../id';

describe('id - delegation ID generation', () => {
    describe('generateId', () => {
        it('should generate IDs in the format adjective-color-animal', () => {
            const id = generateId();
            const parts = id.split('-');
            
            expect(parts.length).toBe(3);
            expect(parts[0].length).toBeGreaterThan(0); // adjective
            expect(parts[1].length).toBeGreaterThan(0); // color
            expect(parts[2].length).toBeGreaterThan(0); // animal
        });

        it('should generate different IDs on subsequent calls (usually)', () => {
            const ids = new Set<string>();
            const numIds = 50;

            for (let i = 0; i < numIds; i++) {
                ids.add(generateId());
            }

            // Due to random selection, we expect most IDs to be unique
            // But collisions are possible with ~107k combinations
            expect(ids.size).toBeGreaterThan(numIds * 0.8);
        });

        it('should only use lowercase letters and hyphens', () => {
            for (let i = 0; i < 20; i++) {
                const id = generateId();
                expect(id).toMatch(/^[a-z]+-[a-z]+-[a-z]+$/);
            }
        });
    });

    describe('generateUniqueId', () => {
        it('should generate IDs in the format adjective-color-animal-timestamp', () => {
            const id = generateUniqueId();
            const parts = id.split('-');
            
            expect(parts.length).toBe(4);
            expect(parts[0].length).toBeGreaterThan(0); // adjective
            expect(parts[1].length).toBeGreaterThan(0); // color
            expect(parts[2].length).toBeGreaterThan(0); // animal
            expect(/^\d+$/.test(parts[3])).toBe(true); // timestamp (numeric)
        });

        it('should generate unique IDs for sequential calls', () => {
            const ids = new Set<string>();
            const numIds = 100;

            for (let i = 0; i < numIds; i++) {
                const id = generateUniqueId();
                expect(ids.has(id)).toBe(false);
                ids.add(id);
            }

            expect(ids.size).toBe(numIds);
        });

        it('should use current timestamp', () => {
            const beforeTs = Date.now();
            const id = generateUniqueId();
            const afterTs = Date.now();

            const parts = id.split('-');
            const timestamp = parseInt(parts[3], 10);

            expect(timestamp).toBeGreaterThanOrEqual(beforeTs);
            expect(timestamp).toBeLessThanOrEqual(afterTs);
        });

        it('should generate different timestamps for rapid calls', async () => {
            const id1 = generateUniqueId();
            
            // Wait a tiny bit to ensure timestamp changes
            await new Promise((resolve) => setTimeout(resolve, 2));
            
            const id2 = generateUniqueId();

            const ts1 = parseInt(id1.split('-')[3], 10);
            const ts2 = parseInt(id2.split('-')[3], 10);

            expect(ts2).toBeGreaterThanOrEqual(ts1);
        });

        it('should handle concurrent generation without collisions', () => {
            const ids = new Set<string>();
            const promises = [];

            for (let i = 0; i < 100; i++) {
                promises.push(
                    new Promise<string>((resolve) => {
                        resolve(generateUniqueId());
                    })
                );
            }

            return Promise.all(promises).then((results) => {
                results.forEach((id) => {
                    expect(ids.has(id)).toBe(false);
                    ids.add(id);
                });
                expect(ids.size).toBe(100);
            });
        });
    });

    describe('isValidId', () => {
        describe('standard format (3 parts)', () => {
            it('should validate IDs generated by generateId', () => {
                for (let i = 0; i < 20; i++) {
                    const id = generateId();
                    expect(isValidId(id)).toBe(true);
                }
            });

            it('should accept valid adjective-color-animal combinations', () => {
                expect(isValidId('swift-amber-falcon')).toBe(true);
                expect(isValidId('bold-coral-panther')).toBe(true);
                expect(isValidId('calm-jade-tiger')).toBe(true);
            });

            it('should reject IDs with invalid adjectives', () => {
                expect(isValidId('invalid-amber-falcon')).toBe(false);
                expect(isValidId('xyz-coral-panther')).toBe(false);
            });

            it('should reject IDs with invalid colors', () => {
                expect(isValidId('swift-invalid-falcon')).toBe(false);
                expect(isValidId('bold-xyz-panther')).toBe(false);
            });

            it('should reject IDs with invalid animals', () => {
                expect(isValidId('swift-amber-invalid')).toBe(false);
                expect(isValidId('bold-coral-xyz')).toBe(false);
            });
        });

        describe('unique format with timestamp (4 parts)', () => {
            it('should validate IDs generated by generateUniqueId', () => {
                for (let i = 0; i < 20; i++) {
                    const id = generateUniqueId();
                    expect(isValidId(id)).toBe(true);
                }
            });

            it('should accept valid adjective-color-animal-timestamp combinations', () => {
                expect(isValidId('swift-amber-falcon-1706345678901')).toBe(true);
                expect(isValidId('bold-coral-panther-1234567890123')).toBe(true);
                expect(isValidId('calm-jade-tiger-9876543210987')).toBe(true);
            });

            it('should reject IDs with non-numeric timestamps', () => {
                expect(isValidId('swift-amber-falcon-abc')).toBe(false);
                expect(isValidId('bold-coral-panther-123abc')).toBe(false);
                expect(isValidId('calm-jade-tiger-12.34')).toBe(false);
            });

            it('should reject IDs with invalid words but valid timestamp', () => {
                expect(isValidId('invalid-amber-falcon-1706345678901')).toBe(false);
                expect(isValidId('swift-invalid-falcon-1706345678901')).toBe(false);
                expect(isValidId('swift-amber-invalid-1706345678901')).toBe(false);
            });
        });

        describe('edge cases', () => {
            it('should reject empty strings', () => {
                expect(isValidId('')).toBe(false);
            });

            it('should reject IDs with too few parts', () => {
                expect(isValidId('swift-amber')).toBe(false);
                expect(isValidId('swift')).toBe(false);
            });

            it('should reject IDs with too many parts', () => {
                expect(isValidId('swift-amber-falcon-123-extra')).toBe(false);
            });

            it('should reject IDs with uppercase letters', () => {
                expect(isValidId('Swift-amber-falcon')).toBe(false);
                expect(isValidId('swift-Amber-falcon')).toBe(false);
                expect(isValidId('swift-amber-Falcon')).toBe(false);
            });

            it('should reject IDs with spaces', () => {
                expect(isValidId('swift amber falcon')).toBe(false);
                expect(isValidId('swift-amber falcon')).toBe(false);
            });

            it('should reject IDs with special characters', () => {
                expect(isValidId('swift-amber-falcon!')).toBe(false);
                expect(isValidId('swift@amber-falcon')).toBe(false);
                expect(isValidId('swift-amber_falcon')).toBe(false);
            });

            it('should reject IDs with leading/trailing hyphens', () => {
                expect(isValidId('-swift-amber-falcon')).toBe(false);
                expect(isValidId('swift-amber-falcon-')).toBe(false);
            });

            it('should reject IDs with double hyphens', () => {
                expect(isValidId('swift--amber-falcon')).toBe(false);
                expect(isValidId('swift-amber--falcon')).toBe(false);
            });
        });

        describe('backward compatibility', () => {
            it('should accept both old (3-part) and new (4-part) formats', () => {
                // Old format (from generateId)
                expect(isValidId('swift-amber-falcon')).toBe(true);
                
                // New format (from generateUniqueId)
                expect(isValidId('swift-amber-falcon-1706345678901')).toBe(true);
            });
        });
    });
});
